-- 咕咕看板：用户关注/收藏/持仓/资产汇总
-- 建议由后端（service role）执行，客户端不直接写 Supabase

create extension if not exists pgcrypto;

-- 用户基础信息（按 openid 维度）
create table if not exists public.user_profiles (
  id uuid primary key default gen_random_uuid(),
  openid text not null unique,
  nickname text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 用户关注基金（含收藏状态）
create table if not exists public.user_funds (
  id bigint generated by default as identity primary key,
  openid text not null,
  fund_code text not null,
  fund_name text not null default '',
  favorite boolean not null default false,
  group_id text not null default 'default',
  sort_order integer not null default 0,
  add_time bigint,
  client_update_time bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_funds_openid_code_uk unique (openid, fund_code)
);

create index if not exists idx_user_funds_openid on public.user_funds(openid);
create index if not exists idx_user_funds_openid_favorite on public.user_funds(openid, favorite);

-- 用户持仓（fund_code 一对一）
create table if not exists public.user_holdings (
  id bigint generated by default as identity primary key,
  openid text not null,
  fund_code text not null,
  mode text not null default 'amount' check (mode in ('amount', 'shares')),
  amount numeric(18, 4),
  shares numeric(18, 6),
  cost_price numeric(18, 6),
  first_buy_date date,
  client_update_time bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_holdings_openid_code_uk unique (openid, fund_code)
);

create index if not exists idx_user_holdings_openid on public.user_holdings(openid);

-- 用户资产汇总（实时快照，一用户一行）
create table if not exists public.user_portfolio_summary (
  openid text primary key,
  fund_count integer not null default 0,
  favorite_count integer not null default 0,
  holding_count integer not null default 0,
  total_cost numeric(18, 2) not null default 0,
  total_market_value numeric(18, 2) not null default 0,
  today_pnl numeric(18, 2) not null default 0,
  total_pnl numeric(18, 2) not null default 0,
  total_pnl_rate numeric(12, 4) not null default 0,
  snapshot_date date not null default current_date,
  client_sync_at bigint,
  updated_at timestamptz not null default now()
);

-- 可选：同步日志，用于排障
create table if not exists public.sync_logs (
  id bigint generated by default as identity primary key,
  openid text not null,
  sync_type text not null, -- full / increment
  payload_size integer not null default 0,
  success boolean not null default true,
  message text,
  created_at timestamptz not null default now()
);

create index if not exists idx_sync_logs_openid_created_at on public.sync_logs(openid, created_at desc);

-- 更新时间触发器
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_funds_updated_at on public.user_funds;
create trigger trg_user_funds_updated_at
before update on public.user_funds
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_holdings_updated_at on public.user_holdings;
create trigger trg_user_holdings_updated_at
before update on public.user_holdings
for each row execute function public.set_updated_at();

-- ===== RLS（若未来改为直连 Supabase，可启用）=====
alter table public.user_profiles enable row level security;
alter table public.user_funds enable row level security;
alter table public.user_holdings enable row level security;
alter table public.user_portfolio_summary enable row level security;
alter table public.sync_logs enable row level security;

-- 约定 JWT claim 中有 openid
-- auth.jwt() ->> 'openid'

drop policy if exists p_user_profiles_self on public.user_profiles;
create policy p_user_profiles_self on public.user_profiles
for all using (openid = auth.jwt() ->> 'openid')
with check (openid = auth.jwt() ->> 'openid');

drop policy if exists p_user_funds_self on public.user_funds;
create policy p_user_funds_self on public.user_funds
for all using (openid = auth.jwt() ->> 'openid')
with check (openid = auth.jwt() ->> 'openid');

drop policy if exists p_user_holdings_self on public.user_holdings;
create policy p_user_holdings_self on public.user_holdings
for all using (openid = auth.jwt() ->> 'openid')
with check (openid = auth.jwt() ->> 'openid');

drop policy if exists p_user_portfolio_summary_self on public.user_portfolio_summary;
create policy p_user_portfolio_summary_self on public.user_portfolio_summary
for all using (openid = auth.jwt() ->> 'openid')
with check (openid = auth.jwt() ->> 'openid');

drop policy if exists p_sync_logs_self on public.sync_logs;
create policy p_sync_logs_self on public.sync_logs
for select using (openid = auth.jwt() ->> 'openid');
